---
# See ../DEPENDENCIES.md for more information
name: Dependabot hack
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - never-trigger-this-dependabot-workflow

jobs:

  dependabot_hack:
    name: Ensure dependabot version checks
    runs-on: ubuntu-20.04
    steps:
      # update the version in these places manually when Dependabot changes it here:
      # 1. /super/abseil.cmake
      - uses: abseil/abseil-cpp@20210324.1
      # 2. /google/cloud/*/quickstart/WORKSPACE
      - uses: googleapis/google-cloud-cpp@v1.26.0
